version: '2.1'

services:
  test-mysql:
    image: mysql:5
    volumes:
      - cas-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=bla
    expose:
      - "3306"
    networks:
      - cas-network-dc
    restart: "no"
    healthcheck:
        test: ["CMD", "mysql", "-uroot", "-p123","-e","CREATE DATABASE IF NOT EXISTS bla"]
        interval: 10s
        timeout: 5s
        retries: 2
  cas-demo:
    depends_on:
      test-mysql:
        condition: service_healthy
    image: team-dijkstra/course-assessement-system
    expose:
      - "4040"
    networks:
      - cas-network-dc
    restart: "no"
  cas-frontend:
    depends_on:
      - cas-demo
      - test-mysql
    image: team-dijkstra/cas-frontend
    networks:
      - cas-network-dc
    ports:
      - "7070:80"
    restart: "no"
networks:
  cas-network-dc:
    driver: bridge
volumes:
  cas-db-data: